services:
  # Backend API Service
  - type: web
    name: lingualearner-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: lingualearner-db
          property: connectionString
    healthCheckPath: /health

  # Frontend Web Service  
  - type: web
    name: lingualearner-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: lingualearner-api
          property: host

# Database
databases:
  - name: lingualearner-db
    plan: free
    databaseName: lingualearner
    user: lingualearner_user